[package]

name = "rust-notes"
version = "0.0.1"
authors = ["Ethan Frei <ethan.frei@gmail.com>"]

[dependencies.handlebars]

git = "https://github.com/sunng87/handlebars-rust.git"

[dependencies]

docopt = "*"
rustc-serialize = "*"

