[package]

name = "rust-notes"
version = "0.0.1"
authors = ["Ethan Frei <ethan.frei@gmail.com>"]
edition = "2018"

[dependencies]

handlebars = "3.5"
docopt = "1.1"
pulldown-cmark = "0.8"
serde = "1.0"
serde_json = "1.0"
