[package]

name = "rust-notes"
version = "0.0.1"
authors = ["Ethan Frei <ethan.frei@gmail.com>"]
edition = "2018"

[dependencies]

handlebars = "*"
docopt = "1"
pulldown-cmark = "*"
serde = "1"
serde_json = "1"
